// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iehgfvqcspyjsqapygnk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImllaGdmdnFjc3B5anNxYXB5Z25rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3Njk4MDAsImV4cCI6MjA2NDM0NTgwMH0.dfz4FFniGxORQNNq_saKyVI0aCZAZHfChspXi6spuhs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);